name: berk-drl-hw1
channels:
  - defaults
dependencies:
  - python=3.5
  - pip:
    - mlflow==1.1.0
    - gym==0.10.5
    - mujoco-py==1.50.1.56
    - tensorflow==1.14.0
    - numpy==1.17.0
    - seaborn==0.9.0
    - scikit-learn==0.21.3
